from django.conf.urls import url

from . import views

urlpatterns = [
               url(r'^$', views.index, name='index'),
               url(r'^index', views.index, name='index'),
               url(r'^login', views.login, name = 'login'),
               url(r'^charts',views.charts, name = 'charts'),
               url(r'^tables',views.tables, name = 'tables'),
               url(r'^register',views.register, name = 'register'),
               url(r'^forgotPassword',views.forgot, name = 'forgot-Password'),
               url(r'^404',views.badPage, name = '404Page'),
               url(r'^blank',views.blank, name = 'blank'),
               url(r'^teamtables', views.teamtables, name = 'teamtables'),
               url(r'^Golden State Warriors', views.GoldenState, name = 'GSW'),
               url(r'^Playoff', views.playoffs, name = 'Playoffs'),
               url(r'^Champions', views.Champions, name = 'Champs'),
               url(r'^Atlanta Hawks', views.Atlanta, name = 'ATL'),
               url(r'^Boston Celtics', views.Boston, name = 'BOS'),
               url(r'^Brooklyn Nets', views.Brooklyn, name = 'BKN'),
               url(r'^Charlotte Hornets', views.Charlotte, name = 'CHA'),
               url(r'^Chicago Bulls', views.Chicago, name = 'CHI'),
               url(r'^Cleveland Cavaliers', views.Cleveland, name = 'CLE'),
               url(r'^Dallas Mavericks', views.Dallas, name = 'DAL'),
               url(r'^Denver Nuggets', views.Denver, name = 'Den'),
               url(r'^Detroit Pistons', views.Detroit, name = 'DET'),
               url(r'^Houston Rockets', views.Houston, name = 'HOU'),
               url(r'^Indiana Pacers', views.Indiana, name = 'IND'),
               url(r'^Los Angeles Clippers', views.LAC, name = 'LAC'),
               url(r'^Los Angeles Lakers', views.LAL, name = 'LAL'),
               url(r'^Memphis Grizzlies', views.Memphis, name = 'Mem'),
               url(r'^Miami Heat', views.Miami, name = 'MIA'),
               url(r'^Milwaukee Bucks', views.Milwaukee, name = 'MIL'),
               url(r'^Minnesota Timberwolves', views.Minnesota, name = 'MIN'),
               url(r'^New Orleans Pelicans', views.NOP, name = 'NOP'),
               url(r'^New York Knicks', views.NY, name = 'NYK'),
               url(r'^Oklahoma City Thunder', views.OKC, name = 'OKC'),
               url(r'^Orlando Magic', views.Orlando, name = 'ORL'),
               url(r'^Philadelphia 76ers', views.PHILA, name = 'PHIL'),
               url(r'^Phoenix Suns', views.SUNS, name = 'SUNS'),
               url(r'^Portland Trail blazers', views.Portland, name = 'port'),
               url(r'^Sacramento Kings', views.SAC, name = 'SAC'),
               url(r'^San Antonio Spurs', views.SAS, name = 'SASA'),
               url(r'^Toronto Raptors', views.TOR, name = 'TOR'),
               url(r'^Utah Jazz', views.UTAH, name = 'UTA'),
               url(r'^Washington Wizards', views.WASH, name = 'WAS'),

]
